--- #YAML:1.0
name:               Gtk2-Ex-ErrorTextDialog
version:            4
abstract:           Dialog showing error messages in a TextView.
author:
    - Kevin Ryde <user42@zip.com.au>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Devel::GlobalDestruction:  0
    Glib:                 0
    Glib::Ex::SignalIds:  0
    Glib::Ex::SourceIds:  0
    Glib::Object::Subclass:  0
    Gtk2:                 0
    Gtk2::Pango:          0
    Locale::Messages:     0
    Locale::TextDomain:   1.16
resources:
    homepage:  http://user42.tuxfamily.org/gtk2-ex-errortextdialog/index.html
    license:   http://www.gnu.org/licenses/gpl.html
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
optional_features:
    maximum_devel:
        description:  Stuff used variously for development.
        requires:
            Devel::Loading:  0
            lib::abs:        0
    maximum_examples:
        description:  Be able to run all the examples programs.
        requires:
            Test::Weaken:  3
    maximum_tests:
        description:  Have "make test" do as much as possible.
        requires:
            File::Spec:          0
            FindBin:             0
            Parse::CPAN::Meta:   0
            Test::DistManifest:  0
            Test::NoWarnings:    0
            Test::Pod:           1.00
            YAML:                0
            YAML::Syck:          0
            YAML::Tiny:          0
            YAML::XS:            0
