--- #YAML:1.0
name:                Gtk2-Ex-ErrorTextDialog
version:             1
abstract:            Dialog showing error messages in a TextView.
license:             gpl
author:              
    - Kevin Ryde <user42@zip.com.au>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Glib::Ex::SignalIds:           0
    Gtk2:                          0
    Gtk2::Pango:                   0
    Locale::Messages:              0
    Locale::TextDomain:            1.16
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
optional_features:
    maximum_tests:
        description: Have "make test" do as much as possible.
        requires:
            Test::Pod: 1.00
            Test::Weaken: 1.002
no_index:
    directory:
        - devel
resources:
    homepage: http://www.geocities.com/user42_kevin/gtk2-ex-errortextdialog/index.html
    license: http://www.gnu.org/licenses/#GPL
